#!/usr/bin/env python3
"""Unit tests for the B-017-Lite policy validator."""

import importlib
import os
import shutil
import tempfile
import unittest
from pathlib import Path

try:
    import b017_lite_policy_validator as pv
except ImportError:
    from tools.security import b017_lite_policy_validator as pv


class B017LitePolicyValidatorTests(unittest.TestCase):
    def setUp(self):
        self.original_repo_root = pv.REPO_ROOT
        self.td = Path(tempfile.mkdtemp(prefix="b017_lite_test_"))
        pv.REPO_ROOT = self.td

    def tearDown(self):
        pv.REPO_ROOT = self.original_repo_root
        shutil.rmtree(self.td, ignore_errors=True)

    def _write_good_files(self):
        (self.td / ".github" / "workflows").mkdir(parents=True)
        (self.td / ".github" / "workflows" / "ci.yml").write_text(
            "on:\n  push:\n    branches: [main]\n\n"
            "permissions:\n  contents: read\n\n"
            "jobs:\n  test:\n    runs-on: ubuntu-latest\n"
            "    steps:\n      - uses: actions/checkout@" + ("a" * 40) + " # v4\n",
            encoding="utf-8",
        )

        (self.td / "gradle" / "wrapper").mkdir(parents=True)
        (self.td / "gradle" / "wrapper" / "gradle-wrapper.properties").write_text(
            "distributionUrl=https\\://services.gradle.org/distributions/gradle-9.3.1-bin.zip\n"
            "distributionSha256Sum=b266d5ff6b90eada6dc3b20cb090e3731302e553a27c5d3e4df1f0d76beaff06\n"
            "validateDistributionUrl=true\n",
            encoding="utf-8",
        )

        (self.td / "build.gradle.kts").write_text(
            "plugins { id(\"com.android.application\") version \"8.13.2\" }\n"
            "dependencies { implementation(\"androidx.core:core-ktx:1.12.0\") }\n",
            encoding="utf-8",
        )

        (self.td / "settings.gradle.kts").write_text(
            "dependencyResolutionManagement {\n"
            "  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)\n"
            "  repositories {\n"
            "    google()\n"
            "    mavenCentral()\n"
            "    gradlePluginPortal()\n"
            "  }\n"
            "}\n",
            encoding="utf-8",
        )

        (self.td / "crypto" / "rust").mkdir(parents=True)
        (self.td / "crypto" / "rust" / "Cargo.toml").write_text(
            "[package]\nname = \"anox_crypto\"\nversion = \"0.1.0\"\n\n"
            "[dependencies]\nvodozemac = \"0.10.0\"\n",
            encoding="utf-8",
        )
        (self.td / "crypto" / "rust" / "Cargo.lock").write_text(
            "# generated by cargo\nversion = 4\n", encoding="utf-8"
        )
        (self.td / ".gitignore").write_text("/local.properties\n", encoding="utf-8")

    def test_all_good_passes(self):
        self._write_good_files()
        self.assertEqual(pv.main(), 0)

    def test_floating_action_ref_fails(self):
        self._write_good_files()
        ci = self.td / ".github" / "workflows" / "ci.yml"
        text = ci.read_text(encoding="utf-8")
        ci.write_text(text.replace(("a" * 40) + " # v4", "v4"), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_pull_request_target_fails(self):
        self._write_good_files()
        ci = self.td / ".github" / "workflows" / "ci.yml"
        text = ci.read_text(encoding="utf-8")
        ci.write_text(text.replace("on:\n  push:\n    branches: [main]", "on:\n  pull_request_target:\n    branches: [main]"), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_contents_write_permission_fails(self):
        self._write_good_files()
        ci = self.td / ".github" / "workflows" / "ci.yml"
        text = ci.read_text(encoding="utf-8")
        ci.write_text(text.replace("permissions:\n  contents: read", "permissions:\n  contents: write"), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_missing_gradle_wrapper_checksum_fails(self):
        self._write_good_files()
        props = self.td / "gradle" / "wrapper" / "gradle-wrapper.properties"
        text = props.read_text(encoding="utf-8")
        props.write_text(text.replace("distributionSha256Sum=b266d5ff6b90eada6dc3b20cb090e3731302e553a27c5d3e4df1f0d76beaff06\n", ""), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_dynamic_gradle_version_fails(self):
        self._write_good_files()
        build = self.td / "build.gradle.kts"
        text = build.read_text(encoding="utf-8")
        build.write_text(text.replace(":1.12.0\"", ":+\""), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_insecure_gradle_repo_fails(self):
        self._write_good_files()
        settings = self.td / "settings.gradle.kts"
        text = settings.read_text(encoding="utf-8")
        settings.write_text(text.replace("google()", 'maven { url = uri("http://insecure.example.com") }\n    google()'), encoding="utf-8")
        self.assertEqual(pv.main(), 1)

    def test_missing_cargo_lock_fails(self):
        self._write_good_files()
        (self.td / "crypto" / "rust" / "Cargo.lock").unlink()
        self.assertEqual(pv.main(), 1)

    def test_wildcard_cargo_dependency_fails(self):
        self._write_good_files()
        cargo = self.td / "crypto" / "rust" / "Cargo.toml"
        text = cargo.read_text(encoding="utf-8")
        cargo.write_text(text.replace('vodozemac = "0.10.0"', 'vodozemac = "*"'), encoding="utf-8")
        self.assertEqual(pv.main(), 1)


if __name__ == "__main__":
    unittest.main()
